name: Deploy Build

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create a tree of the repo
        run: tree . -H . -P '*.7z|*.z*|*.html' -o index.html

      - name: Push changes to repo
        run: |
          git config user.name bulletproofpancake
          git config user.email 57520402+bulletproofpancake@users.noreply.github.com
          git add index.html
          git commit -m '${{ github.event.repository.updated_at}}'
          git push

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1.9.0
        if: success()
        with:
          webhook: ${{secrets.DISCORD_WEBHOOK_BUILD}}
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          url: "https://woahpiestudios.github.io/gdelect4-advaprod-builds/"
